site:
    title: "巫部親雲上的博客"
    subtitle: "我十分想见赵忠祥"
    limit: 16
    theme: theme
    lang: zh
    url: "https://kannagi.moe/blog"
    comment: KannagiPeekumii
    logo: "-/images/zhihu_avatar.jpg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    root: "/blog"

authors:
    me:
        name: "巫部親雲上"
        intro: "有理想、有道德、有文化、有纪律"
        avatar: "-/images/zhihu_avatar.jpg"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
