site:
    title: "Kannagi Pēkumī's Blog"
    subtitle: "关注计算机技术、自然语言、东亚文化以及各种有趣的事物"
    limit: 10
    theme: theme
    lang: en
    url: "https://kannagi.moe/blog"
    comment: kannagi-moe
    logo: "-/images/zhihu_avatar.jpg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    root: "/blog"

authors:
    me:
        name: "巫部親雲上"
        intro: "In solitude, where we are least alone."
        avatar: "-/images/zhihu_avatar.jpg"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
